# Generated by .github/workflows/release.yml in mrsmsn/issue. Do not edit by hand.
class Issue < Formula
  desc "Local-first issue-management CLI with a lazygit-style TUI (lazyissue)"
  homepage "https://github.com/mrsmsn/issue"
  version "@VERSION@"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mrsmsn/issue/releases/download/v@VERSION@/issue_@VERSION@_darwin_arm64.tar.gz"
      sha256 "@SHA256_ARM64@"
    end
    on_intel do
      url "https://github.com/mrsmsn/issue/releases/download/v@VERSION@/issue_@VERSION@_darwin_amd64.tar.gz"
      sha256 "@SHA256_AMD64@"
    end
  end

  def install
    bin.install "issue"
    bin.install "lazyissue"

    # Run the just-installed binary to emit completions; installed into
    # Homebrew's completion dirs (already on the user's fpath) — so
    # `issue <Tab>` works with no `source` line, like gh.
    generate_completions_from_executable(
      bin/"issue", "completions",
      base_name: "issue", shells: [:bash, :zsh, :fish]
    )
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/issue --version")
    assert_match version.to_s, shell_output("#{bin}/lazyissue --version")
  end
end
