# Generated by .github/workflows/release.yml in mrsmsn/issue. Do not edit by hand.
class Issue < Formula
  desc "Local-first issue-management CLI with a lazygit-style TUI (lazyissue)"
  homepage "https://github.com/mrsmsn/issue"
  url "https://github.com/mrsmsn/issue/archive/refs/tags/v@VERSION@.tar.gz"
  sha256 "@SHA256@"
  license "MIT"
  head "https://github.com/mrsmsn/issue.git", branch: "main"

  depends_on "rust" => :build

  def install
    # Build & install both workspace binaries the idiomatic Homebrew way
    # (std_cargo_args = --locked --root <prefix> --path <crate>).
    system "cargo", "install", *std_cargo_args(path: "crates/cli")
    system "cargo", "install", *std_cargo_args(path: "crates/tui")

    # Installs _issue / issue.bash / issue.fish into Homebrew's completion
    # dirs (already on the user's fpath) — so `issue <Tab>` works with no
    # `source` line, exactly like gh.
    generate_completions_from_executable(
      bin/"issue", "completions",
      base_name: "issue", shells: [:bash, :zsh, :fish]
    )
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/issue --version")
    assert_match version.to_s, shell_output("#{bin}/lazyissue --version")
    assert_match "Usage: issue", shell_output("#{bin}/issue --help")
  end
end
